= Lecture Notes / 3BHITM / ITP
Thomas Spindler
1.0.0, {docdate}: ITP
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

== 02.12.2021

Buch S. 81: Projekt-Start-up-Workshop

=== ITP:
Projekte
ProjektvorgehensModelle
IPT vereint Mathematik, English, SEW, und weitere in ein Fach

Wie kann ich ein Projekt durchführen?
(Teams, zusammenarbeit, Codesicherung)
oft einfach nur eine art von Checklisten abarbeiten

Buch S. 84: Organisationsformen
Beispiel Mondlandung (alles auf eine Aufgabe (Task force)

Unternehmensbereich:

* Einkauf
* Verkauf
* Verwaltung
* Werkstätte
* usw

Strategien:

* Strategie (2-4 Jahre)		z.B: Produktoptionen
* Taktiv (1 Jahr)			z.B: verwendete Maschinen
* operatives Vorgehen (unmittelbar)	z.B: Arbeitszeiten (Schichtbetrieb)

    HÜ: S. 85 lesen (Kapitel 2 fertig)

vcs = version controlling System

vcs braucht man um während des Entwickelns zurückgehen kann, wenn es Fehler gibt.

Arten von VCS:

== 07.12.2021

=== Test

Test kann man sich jederzeit in der Schule abholen, bekanntgeben nach Ablauf der gesetzlichen Frist (Donnerstag)

Kein Wiederholungstest aufgrund zu weniger 5er.

=== Git

Status des GitRepositories:

    git status
    git status -s [For better file overview]

Git restore staged Files (unstaging):

    git restore --staged .["." für alle Dateien]

verstehen des Git staging Systems

zum Hinzufügen eines Files in ein Git System

    git add <FILENAME>

Staging in Git:

    -> auswählen welche Dateien und Verzeichnisse ins Repo gesichert werden sollten

Änderungen bis zu m letzten Commit zurücksetzen:

    git restore .
    git restore <FILE>

Löschen neu erstellter Files:

    git clean -f

== 14.12.2021

Origin hinzufügen mit

    git origin add <LINK>

=== Git Branches
Branches sind pointer auf den letzen Commit des Master branches +
ein Repository kann beliebig viele Branches haben. +

== Lecture 21.12.2021

=== Github Keygen

mithilfe von SSH keys:

    ssh-keygen -t rsa
    ssh-add ~/.ssh/<KEYNAME (id_rsa)>
    git config --global user.name "<YOUR USERNAME>"
    git config --global user.email "<YOUR EMAIL">

== GIT:

neuen Ordner erstellen und erneut Klonen

    mkdir work
    cd work
    git clone <LINK>

File im Directory abändern:

    gedit readme.md
    <ändern des files>
    git commit -m "test merge"
    git push

Andere Person nun auf dem repo:

    git status

man bemerkt, dass das Repo nicht auf dem aktuellen Stand ist +
updaten des Repos:

    git pull

mit diesen Command laded man alle Abänderungen in den
Dateien des remote repos herunter.

Person 2 editiert dann die Datei, committed und pusht

    echo "Person 2 edit" >> readme.md
    git commit -m "update readme.md - Person 2"
    git push

Person 1 ladet nun wieder die Abänderungen herunter

    git pull

nun ändern beide Personen die Datei readme.md ab. +
beide Personen:

    git add
    git commit -m "merge test2"
    git push

bei einer Person wird der push rejected, da das Remote
repo Änderungen beinhaltet, die noch nicht existieren. +
Daher braucht man git stash:

    git stash

aufgrund des Commites kann stash nicht ausgeführt werden.

IMPORTANT: vor dem commit *IMMER* einen pull machen

Öffnen des Repos in IntelliJ für einen Merge +
Mergeconflikte sind auf der Commandline eher schwer zu machen,
daher sollten wir dafür einen Editor verwenden (IntelliJ, VSCode).

Man kann dafür auch andere Programme verwenden, z.B Github desktop

== 23.12.2021 GIT Merge

=== idea . Command:

Öffnen eines Ordners mit den Command "idea .":

IMPORTANT: Alle Jetbrains Produkte über die Toolbox installieren

    Toolbox settings
    > Tools
    > generate shell scripts auf on
    > Ordner: /home/idea-scripts
    Apply

im Ordner /home/idea-scripts sollten nun die Scripts generiert worden sein.

=== Git Merge mit IntelliJ:

    git pull (blauer Pfeil)
    mergen
    dann auf dem Interface auswählen bis alles passt

IMPORTANT: HÜ: OraVM hinbekommen und dokumentieren

=== IT Merge 2 (Mitschrift Thomas Spindler)
11.01.2022

Alle pullen das aktuelle Repo

    git pull

dann ändern alle die Selbe Zeile ab.
Und diese commiten und pushen dann alle die Abänderungen auf das Repo:

    git commit -m "<MESSAGE>"
    git push

Daraufhin entsteht ein Mergekonflint. Das Pushen wird nur bei einer Person funktionieren.

==== GIT stash:

Stashen mithilfe von:

    git stash

Dies funktioniert nicht, da wir gepullt haben. Git stash muss vor dem pull ausgeführt werden.

'''

Alle pullen das aktuelle Repo

    git pull

dann ändern alle die Selbe Zeile ab.
Eine Peron pusht dann auf das Repo:

    git commit -m "<MESSAGE>"
    git push

Bei der anderen Person, stashen wir zuerst die Änderungen, und dann pullen wir alles vom remote Repo.

    git stash
    git pull

Hiermit verstecken wir alle unsere aktuellen Änderungen, und speichere diese Abänderungen zwischen
Dann hohlen wir uns die neuesten Änderungen vom Repo. +
Mit dem folgenden Command holen wir die Änderungen wieder zurück:

    git stash pop

Git pulls sollten regelmäßig und oft gemacht werden, um größere Konflikte zu verhindern. +
Dies kann auch in IntelliJ automatisiert werden.

    > settings
    > git
    > Explicitly check for incoming commits on remotes: always