= Lecture Notes / 3BHITM / ITP
Thomas Spindler
1.0.0, {docdate}: ITP
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

== 02.12.2021

Buch S. 81: Projekt-Start-up-Workshop

=== ITP:
Projekte
ProjektvorgehensModelle
IPT vereint Mathematik, English, SEW, und weitere in ein Fach

Wie kann ich ein Projekt durchführen?
(Teams, zusammenarbeit, Codesicherung)
oft einfach nur eine art von Checklisten abarbeiten

Buch S. 84: Organisationsformen
Beispiel Mondlandung (alles auf eine Aufgabe (Task force)

Unternehmensbereich:

* Einkauf
* Verkauf
* Verwaltung
* Werkstätte
* usw

Strategien:

* Strategie (2-4 Jahre)		z.B: Produktoptionen
* Taktiv (1 Jahr)			z.B: verwendete Maschinen
* operatives Vorgehen (unmittelbar)	z.B: Arbeitszeiten (Schichtbetrieb)

    HÜ: S. 85 lesen (Kapitel 2 fertig)

vcs = version controlling System

vcs braucht man um während des Entwickelns zurückgehen kann, wenn es Fehler gibt.

Arten von VCS:

== 07.12.2021

=== Test

Test kann man sich jederzeit in der Schule abholen, bekanntgeben nach Ablauf der gesetzlichen Frist (Donnerstag)

Kein Wiederholungstest aufgrund zu weniger 5er.

=== Git

Status des GitRepositories:

    git status
    git status -s [For better file overview]

Git restore staged Files (unstaging):

    git restore --staged .["." für alle Dateien]

verstehen des Git staging Systems

zum Hinzufügen eines Files in ein Git System

    git add <FILENAME>

Staging in Git:

    -> auswählen welche Dateien und Verzeichnisse ins Repo gesichert werden sollten

Änderungen bis zu m letzten Commit zurücksetzen:

    git restore .
    git restore <FILE>

Löschen neu erstellter Files:

    git clean -f

== 14.12.2021

Origin hinzufügen mit

    git origin add <LINK>

=== Git Branches
Branches sind pointer auf den letzen Commit des Master branches +
ein Repository kann beliebig viele Branches haben. +

== Lecture 21.12.2021

=== Github Keygen

mithilfe von SSH keys:

    ssh-keygen -t rsa

== GIT:

neuen Ordner erstellen und erneut Klonen

    mkdir work
    cd work
    git clone <LINK>

File im Directory abändern:

    gedit readme.md
    <ändern des files>
    git commit -m "test merge"
    git push

Andere Person nun auf dem repo:

    git status

man bemerkt, dass das Repo nicht auf dem aktuellen Stand ist +
updaten des Repos:

    git pull

mit diesen Command laded man alle Abänderungen in den
Dateien des remote repos herunter.

Person 2 editiert dann die Datei, committed und pusht

    echo "Person 2 edit" >> readme.md
    git commit -m "update readme.md - Person 2"
    git push

Person 1 ladet nun wieder die Abänderungen herunter

    git pull

nun ändern beide Personen die Datei readme.md ab. +
beide Personen:

    git add
    git commit -m "merge test2"
    git push

bei einer Person wird der push rejected, da das Remote
repo Änderungen beinhaltet, die noch nicht existieren. +
Daher braucht man git stash:

    git stash

aufgrund des Commites kann stash nicht ausgeführt werden.

IMPORTANT: vor dem commit IMMER einen pull machen

Öffnen des Repos in Intelliji für einen Merge
Mergeconflikte sind auf der Commandline eher schwer zu machen,
daher sollten wir dafür einen Editor verwenden (Intelliji, VSCode)